namespace: smallstep
name: cli
version: 0.0.1
readme: README.md
authors:
- Tech Admin <techadmin@smallstep.com>
description: Installs the smallstep CLI.
license:
- Apache-2.0
license_file: 'LICENSE.md'
tags:
  - smallstep
  - step
  - step-cli
  - tls
  - mtls
  - pki
  - certificates
dependencies:
  ansible.windows: "=2.0.0"
  smallstep.sigstore: ">=0.0.1"
repository: https://github.com/smallstep/ansible-collection-cli
documentation: https://github.com/smallstep/ansible-collection-cli/README.md
homepage: https://smallstep.com/cli/
issues: https://github.com/smallstep/ansible-collection-cli/issues
build_ignore: []
