---
# defaults file for install
smallstep_cli_version: # Example: v0.24.4. Leave unset for the latest release off of GitHub
smallstep_cli_install_path: /usr/local/bin
smallstep_cli_download_url:
smallstep_cli_verify_signature: True
step_cli_package_format:
