---
# tasks file for install

- name: Performing Tasks to detect OS arch and set step-cli version
  include_tasks: package.yml

- name: Performing step-cli install tasks for Red Hat based distributions
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Performing step-cli package install tasks for Debian based distributions
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Performing step-cli binary install tasks for other operating systems
  include_tasks: other.yml
  when: not (ansible_os_family == "Debian" or ansible_os_family == "RedHat")
