name: Run Ansible Integration Tests

on:
  push:
    tags-ignore:
    - 'v*'
    branches:
    - "main"
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/smallstep/cli

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          path: ansible_collections/smallstep/cli

      - name: Clone Ansible collection dependancy (smallstep.sigstore)
        uses: actions/checkout@v4
        with:
          repository: ansible-collection-sigstore
          path: ansible_collections/smallstep/sigstore

      - name: Clone Ansible collection dependancy (ansible.windows)
        uses: actions/checkout@v4
        with:
          repository: ansible-collections/ansible.windows
          path: ansible_collections/ansible/windows

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip install ansible

      - name: Run the integration tests
        run: ansible-test integration
